### ISSUE TITLE
Reconcile differences with anystyle

### ISSUE THREAD

**Issue by mjy** [bionomia/dwc_agent#2]
How is the code here different, or the same, than tools used by or in anystyle?  There is a lot of sophistication elsewhere that might make code redundant.

**Comment by dshorthouse** [comment]
There's no difference in the basic mechanics, just the intent and class of content both accept. The present gem and Anystyle both have Namae as a dependency. And, both anystyle and Namae are authored by the same person. The present gem differs in handling much of the cruft in DwC terms so is a rather domain-specific cleansing routine prior to passing to Namae. Anystyle as you know is specific to bibliographic citations. I do not believe there is any cause of redundancy unless Namae were refined to permit its own cleansing routine prior to parsing names.

**Comment by mjy** [comment]
Thanks for clarifying to my lazy self, very useful.  I feel like I should have just "googled it" :).

**Comment by dshorthouse** [comment]
It wasn't an unfounded comment because Anystyle itself has a comparable "clean the cruft" normalizer prior to passing content to Namae. See https://github.com/inukshuk/anystyle/blob/master/lib/anystyle/normalizer/names.rb. And, I wasn't very transparent in dependencies nor acknowledged the Namae gem so I fixed the README.
